[workspace]

members = [
    "types",
    "client",
    "server"
]

[workspace.metadata.release]
tag = false
sign-commit = false
consolidate-commits = true
pre-release-commit-message = "chore({{ crate_name }}): Release {{ version }}"

