[package]
name = "stratum-server"
version = "3.4.0"
authors = ["Sean Kilgarriff sean@urkel.com"]
rust-version = "1.60"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "The server code for the Rust Stratum implementation"
repository = "https://github.com/OpenPoolProject/stratum"

[features]
default = ["tcp"]
tcp = []
upstream = []
btcagent = []
v1 = []
v2 = []

[dependencies]

# Futures
# @todo after full implementation, see if we can peel back some features here to
# the minimal required.
tokio = { version = "1.22.0", features = ["full"] }
async-trait = "0.1.58"
futures = "0.3.25"
tokio-util = "0.7.4"
tokio-stream = { version = "0.1.11", features = ["net"]}

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
extended-primitives = {version = "0.3.8"}
encodings = "0.1.0"

# Telemtry
tracing = "0.1.37"

# Primitives
uuid = { version = "1.2.2", features = ["serde", "v4"] }
# default-features only false until new release @note
chrono = { version="0.4.23", default-features = false, features = ["clock"]}

# Utils
thiserror = "1.0.37"
bit-set = "0.5.3"
# @todo I believe we can replace this, but let's see
signal-hook = "0.3.14"
signal-hook-tokio = {version = "0.3.1", features = ["futures-v0_3"]}

[dev-dependencies]
tokio-test = "0.4.2"
portpicker = "0.1.1"

# Allocator @todo switch this to mimalloc
jemallocator = "0.5.0"

tracing-subscriber = {version = "0.3", features = ["env-filter"] }


[package.metadata.release]
tag = false
sign-commit = false
pre-release-commit-message = "chore(server): release {{ version }}"

# @todo bring back benchmarks here.
