[package]
name = "stratum-server"
version = "3.0.0-beta.27"
authors = ["Open Pool Project Developers devs@openpool.dev"]
edition = "2021"
license = "MIT"
description = "The server code for the Rust Stratum implementation"
documentation = "https://docs.rs/stratum-server"
repository = "https://github.com/OpenPoolProject/stratum"
homepage = "https://openpool.dev"

[features]
default = ["tcp"]
tcp = []
websockets = ["async-tungstenite"]

[dependencies]

# Futures
async-std = { version = "1.11", features = ["attributes"] }
async-trait = "0.1.53"
futures = "0.3.21"
stop-token = "0.7.0"
tide = "0.16"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
extended-primitives = {version = "0.3.4"}
encodings = "0.1.0"

# Metrics
# metrics = { version="0.13.0-alpha.8" }
# metrics-exporter-prometheus = "0.1.0-alpha.5"

# Misc
uuid = { version = "1.0.0", features = ["serde", "v4"] }
log = "0.4"
time = "0.3.9"
signal-hook = "0.3.14"
signal-hook-async-std = "0.2.2"
bit-set = "0.5.2"

# Optional
async-tungstenite = { version="0.17.2", features=["async-std-runtime", "async-native-tls"], optional=true}

[dev-dependencies]
criterion = "0.3"
async-std = {version = "1.11.0", features = ["attributes", "unstable"] }
portpicker = "0.1.0"
nix = "0.24"

# Allocator 
# jemallocator = "0.5.3"

#@todo maybe switch this w/ Test_logger.
env_logger = "0.9.0"
serial_test = "0.6.0"

[[bench]]
name = "bench_main"
harness = false

[package.metadata.release]
tag = false
sign-commit = false
pre-release-commit-message = "chore(server): release {{ version }}"
