[package]
name = "stratum-server"
version = "3.4.0"
authors = ["Sean Kilgarriff sean@urkel.com"]
rust-version = "1.60"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "The server code for the Rust Stratum implementation"
repository = "https://github.com/OpenPoolProject/stratum"

[features]
default = ["tcp"]
tcp = []
upstream = []
btcagent = []
v1 = []
v2 = []

[dependencies]

# Futures
async-std = { version = "1.12", features = ["attributes", "unstable"] }
async-trait = "0.1.58"
futures = "0.3.25"
stop-token = "0.7.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
extended-primitives = {version = "0.3.8"}
encodings = "0.1.0"

# Telemtry
tracing = "0.1.37"

# Primitives
uuid = { version = "1.2.1", features = ["serde", "v4"] }
chrono = "0.4.22"


# Utils
thiserror = "1.0.37"
bit-set = "0.5.3"
signal-hook = "0.3.14"
signal-hook-async-std = "0.2.2"

[dev-dependencies]
portpicker = "0.1.1"

# Allocator @todo switch this to mimalloc
jemallocator = "0.5.0"

tracing-subscriber = {version = "0.3", features = ["env-filter"] }


[package.metadata.release]
tag = false
sign-commit = false
pre-release-commit-message = "chore(server): release {{ version }}"

# @todo bring back benchmarks here.
