[package]
name = "bench"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
async-std = { version = "1.12", features = ["attributes", "unstable"] }
stratum-server = { path = "../server" }
criterion = "0.4"

[[bench]]
name = "bench_main"
harness = false
