[package]
name = "proxy"
version = "0.1.0"
authors = ["kilpatty <seanpkilgarriff@gmail.com>"]
edition = "2018"
description = "The client code for the Rust Stratum (v1) implementation."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
