name: Security audit

on:
  schedule:
    # Runs at 00:00 UTC everyday
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c0db65e1f64025718795419be8dbbf8c4050160f
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install Rust
        uses: dtolnay/rust-toolchain@b44cb146d03e8d870c57ab64b80f04586349ca5d
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@b1db5f9d5f9ed685de3a2774c3d3b838d2dde462
      - uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

