name: Security audit

on:
  schedule:
    # Runs at 00:00 UTC everyday
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@613bd0d3f757c824251c115a9ef1b95538fbcc07
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Rust
        uses: dtolnay/rust-toolchain@f7003eed5ea1f2175ea1d670748f9c21af4f5d9e
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8
      - uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

