---
name: ci

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - staging
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  RUST_LOG: info

defaults:
  run:
    shell: bash

jobs:
  test-versions:
    name: Test Suite on ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # if you have an MSRV, you can of course include it here too.
        rust: [stable, beta, nightly]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0b61316f5a3fc8b7b29daa3d9b4a37cd052d11ed
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@e6d535c99c374d0c3f6d8cd8086a57b43c6c700a
      - uses: dtolnay/rust-toolchain@2e4fc08e24c79a982d0b6f4638011718d61c0eee
        with:
          toolchain: ${{ matrix.rust }}
          components: rust-src
      - uses: taiki-e/install-action@e380e63944567f7ed12d3c137af180e095df006a
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@e380e63944567f7ed12d3c137af180e095df006a
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@76686c56f2b581d1bb5bda44b51f7e24bd9b8b8e
        with:
          key: ${{ matrix.rust }}
      - run: cargo hack nextest run --no-capture --each-feature --profile ci
        timeout-minutes: 15

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0b61316f5a3fc8b7b29daa3d9b4a37cd052d11ed
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@e6d535c99c374d0c3f6d8cd8086a57b43c6c700a
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@e380e63944567f7ed12d3c137af180e095df006a
        with:
          tool: cargo-hack
      - run:
          cargo hack build -vvv --workspace --feature-powerset --optional-deps
          --ignore-private --no-dev-deps --version-range ..

  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0b61316f5a3fc8b7b29daa3d9b4a37cd052d11ed
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@e6d535c99c374d0c3f6d8cd8086a57b43c6c700a
      - uses: dtolnay/rust-toolchain@2e4fc08e24c79a982d0b6f4638011718d61c0eee
        with:
          toolchain: nightly
          components: clippy,rustfmt
      - uses: taiki-e/install-action@e380e63944567f7ed12d3c137af180e095df006a
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@e380e63944567f7ed12d3c137af180e095df006a
        with:
          tool: cargo-minimal-versions
      - run: cargo fmt --all --check
        if: always()
      - run: cargo clippy --workspace --all-targets
        if: always()
      - run: cargo minimal-versions build --workspace --ignore-private
        if: always()

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0b61316f5a3fc8b7b29daa3d9b4a37cd052d11ed
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@e6d535c99c374d0c3f6d8cd8086a57b43c6c700a
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@2e4fc08e24c79a982d0b6f4638011718d61c0eee
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@76686c56f2b581d1bb5bda44b51f7e24bd9b8b8e
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: doc
          args: --no-deps --document-private-items --workspace --examples

  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0b61316f5a3fc8b7b29daa3d9b4a37cd052d11ed
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@e6d535c99c374d0c3f6d8cd8086a57b43c6c700a
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@2e4fc08e24c79a982d0b6f4638011718d61c0eee
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@76686c56f2b581d1bb5bda44b51f7e24bd9b8b8e
      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: publish
          args: --dry-run -p stratum-server

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0b61316f5a3fc8b7b29daa3d9b4a37cd052d11ed
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@e6d535c99c374d0c3f6d8cd8086a57b43c6c700a
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@2e4fc08e24c79a982d0b6f4638011718d61c0eee
        with:
          toolchain: stable
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@e380e63944567f7ed12d3c137af180e095df006a
        with:
          tool: cargo-llvm-cov
      - uses: taiki-e/install-action@e380e63944567f7ed12d3c137af180e095df006a
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@v1
      - name: Generate code coverage
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov nextest --profile ci --no-report --features tcp
          cargo llvm-cov --no-run --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
        with:
          files: lcov.info
          fail_ci_if_error: true

  ci-success:
    name: ci
    if: success()
    needs:
      - test-versions
      - msrv
      - tidy
      - docs
      - publish-dry-run
      - coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0b61316f5a3fc8b7b29daa3d9b4a37cd052d11ed
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Mark the job as a success
        run: exit 0
