---
name: ci

permissions: write-all

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - staging
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  RUST_LOG: info

defaults:
  run:
    shell: bash

jobs:
  test-versions:
    name: Test Suite on ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # if you have an MSRV, you can of course include it here too.
        rust: [stable, beta, nightly]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: ${{ matrix.rust }}
          components: rust-src
      - uses: taiki-e/install-action@ab0e193cf5da069d1876bfff4e8967e72df940e3
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@ab0e193cf5da069d1876bfff4e8967e72df940e3
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@664ce0090f15897beb496f9faf2f88e6908c80c4
        with:
          key: ${{ matrix.rust }}
      # - run: cargo hack nextest run --no-capture --each-feature --profile ci
      - run: cargo nextest run --no-capture --all-features --profile ci
        timeout-minutes: 15

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@ab0e193cf5da069d1876bfff4e8967e72df940e3
        with:
          tool: cargo-hack
      - run:
          # cargo hack build -vvv --workspace --feature-powerset --optional-deps
          # --ignore-private --no-dev-deps --version-range ..
          cargo hack build -vvv --workspace --all-features --ignore-private
          --no-dev-deps --version-range ..

  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: nightly
          components: clippy,rustfmt
      - uses: taiki-e/install-action@ab0e193cf5da069d1876bfff4e8967e72df940e3
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@ab0e193cf5da069d1876bfff4e8967e72df940e3
        with:
          tool: cargo-minimal-versions
      - run: cargo fmt --all --check
        if: always()
      - run: cargo clippy --workspace --all-targets
        if: always()
      - run: cargo minimal-versions build --workspace --ignore-private
        if: always()

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@664ce0090f15897beb496f9faf2f88e6908c80c4
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: doc
          args: --no-deps --document-private-items --workspace --examples

  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@664ce0090f15897beb496f9faf2f88e6908c80c4
      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: publish
          args: --dry-run -p stratum-server

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@ab0e193cf5da069d1876bfff4e8967e72df940e3
        with:
          tool: cargo-llvm-cov
      - uses: taiki-e/install-action@ab0e193cf5da069d1876bfff4e8967e72df940e3
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2
      - name: Generate code coverage
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov nextest --profile ci --no-report --all-features
          cargo llvm-cov report --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e0fbd592d323cb2991fb586fdd260734fcb41fcb
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
  bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain:
            stable
            # @todo potentially switch these with Swatinem rust-cache see above.
      - name: Cache cargo registry
        uses: actions/cache@c1a5de879eb890d062a85ee0252d6036480b1fe2 # v3
        with:
          path: ~/.cargo/registry
          key:
            bloat-${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock')
            }}
      - name: Cache cargo index
        uses: actions/cache@c1a5de879eb890d062a85ee0252d6036480b1fe2 # v3
        with:
          path: ~/.cargo/git
          key:
            bloat-${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo bloat
        # @todo For security, let's fork this into the OpenPoolProject/actions
        # folder - the original (this is a fork) no longer works because it uses
        # a 3rd parter server to cache builds that is no longer existant.
        uses: Kobzol/cargo-bloat-action@85b93f37dec06662054e045b5cf1d79cfdb0d748
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bloat_args: -p stratum-server --release --example basic
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: EmbarkStudios/cargo-deny-action@8a8607bd8e2b3a514d5a40174cc7c55b229d9ba7 # v1

  ci-success:
    name: ci
    if: success()
    needs:
      - test-versions
      - msrv
      - tidy
      - docs
      - publish-dry-run
      - coverage
      - bloat
      - cargo-deny
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Mark the job as a success
        run: exit 0
