---
name: ci

permissions: write-all

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - staging
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  RUST_LOG: info

defaults:
  run:
    shell: bash

jobs:
  test-versions:
    name: Test Suite on ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # if you have an MSRV, you can of course include it here too.
        rust: [stable, beta, nightly]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - uses: dtolnay/rust-toolchain@55c7845fad90d0ae8b2e83715cb900e5e861e8cb
        with:
          toolchain: ${{ matrix.rust }}
          components: rust-src
      - uses: taiki-e/install-action@dfd35942fe81dc0cab51f5676ca385dc57e4aebb
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@dfd35942fe81dc0cab51f5676ca385dc57e4aebb
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@b8e72aae8381e4b9942ff10e8ec0fcd359dc5246
        with:
          key: ${{ matrix.rust }}
      - run: cargo hack nextest run --no-capture --each-feature --profile ci
        timeout-minutes: 15

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@dfd35942fe81dc0cab51f5676ca385dc57e4aebb
        with:
          tool: cargo-hack
      - run:
          cargo hack build -vvv --workspace --feature-powerset --optional-deps
          --ignore-private --no-dev-deps --version-range ..

  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - uses: dtolnay/rust-toolchain@55c7845fad90d0ae8b2e83715cb900e5e861e8cb
        with:
          toolchain: nightly
          components: clippy,rustfmt
      - uses: taiki-e/install-action@dfd35942fe81dc0cab51f5676ca385dc57e4aebb
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@dfd35942fe81dc0cab51f5676ca385dc57e4aebb
        with:
          tool: cargo-minimal-versions
      - run: cargo fmt --all --check
        if: always()
      - run: cargo clippy --workspace --all-targets
        if: always()
      - run: cargo minimal-versions build --workspace --ignore-private
        if: always()

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@55c7845fad90d0ae8b2e83715cb900e5e861e8cb
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@b8e72aae8381e4b9942ff10e8ec0fcd359dc5246
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: doc
          args: --no-deps --document-private-items --workspace --examples

  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@55c7845fad90d0ae8b2e83715cb900e5e861e8cb
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@b8e72aae8381e4b9942ff10e8ec0fcd359dc5246
      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: publish
          args: --dry-run -p stratum-server

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@55c7845fad90d0ae8b2e83715cb900e5e861e8cb
        with:
          toolchain: nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@dfd35942fe81dc0cab51f5676ca385dc57e4aebb
        with:
          tool: cargo-llvm-cov
      - uses: taiki-e/install-action@dfd35942fe81dc0cab51f5676ca385dc57e4aebb
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@22c9328bcba27aa81a32b1bef27c7e3c78052531 # tag=v2
      - name: Generate code coverage
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov nextest --profile ci --no-report --features tcp
          cargo llvm-cov report --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e0fbd592d323cb2991fb586fdd260734fcb41fcb
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
  bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@55c7845fad90d0ae8b2e83715cb900e5e861e8cb
        with:
          toolchain:
            stable
            # @todo potentially switch these with Swatinem rust-cache see above.
      - name: Cache cargo registry
        uses: actions/cache@70655ec8323daeeaa7ef06d7c56e1b9191396cbe # tag=v1
        with:
          path: ~/.cargo/registry
          key:
            bloat-${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock')
            }}
      - name: Cache cargo index
        uses: actions/cache@70655ec8323daeeaa7ef06d7c56e1b9191396cbe # tag=v1
        with:
          path: ~/.cargo/git
          key:
            bloat-${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo bloat
        # @todo For security, let's fork this into the OpenPoolProject/actions
        # folder - the original (this is a fork) no longer works because it uses
        # a 3rd parter server to cache builds that is no longer existant.
        uses: Kobzol/cargo-bloat-action@85b93f37dec06662054e045b5cf1d79cfdb0d748
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bloat_args: -p stratum-server --release --example basic
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1

  ci-success:
    name: ci
    if: success()
    needs:
      - test-versions
      - msrv
      - tidy
      - docs
      - publish-dry-run
      - coverage
      - bloat
      - cargo-deny
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Mark the job as a success
        run: exit 0
