---
name: "Dependency Review"
on:
  pull_request:
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Dependency Review
        uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94 # v3
  # critical
  #
  # You can only include one of these two options:
  # `allow-licenses` and `deny-licenses`
  #
  # Possible values: Any `spdx_id` value(s) from
  # https://docs.github.com/en/rest/licenses allow-licenses: GPL-3.0,
  # BSD-3-Clause, MIT
  #
  # Possible values: Any `spdx_id` value(s)
  # from https://docs.github.com/en/rest/licenses deny-licenses: LGPL-2.0,
  # BSD-2-Clause
