name: Auto approve

on: pull_request

permissions: {}

jobs:
  auto-approve:
    if: github.actor == 'kilpatty'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'renovate[bot]' || 'kilpatty'

        with:
          github-token: ${{ steps.generate_token.outputs.token }}
