on:
  push:
    branches:
      - master
name: Release (Please) Generator
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: stratum-server
