on:
  push:
    branches:
      - master
name: Release (Please) Generator
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@c078ea33917ab8cfa5300e48f4b7e6b16606aede # v3
        with:
          release-type: rust
          package-name: stratum-server
          path: server/
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"chore","section":"Miscellaneous","hidden":false},
             {"type":"test","section":"Tests","hidden":true},
             {"type":"ci","section":"Continuous Integration","hidden":true},
             {"type":"docs","section":"Documentation","hidden":true},
             {"type":"refactor","section":"Code Refactoring","hidden":true},
             {"type":"style","section":"Styles","hidden":true}]
